import { getCurrentUser } from "@/util/session";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { redirect } from "next/navigation";

const metadata = {
  title: "SignIn",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  if (!currentUser) {
    redirect("/register");
  }
  return (
    <html lang="en">
      <AntdRegistry>
        <body>{children}</body>
      </AntdRegistry>
    </html>
  );
}
