import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AntdRegistry>
        <body>{children}</body>
      </AntdRegistry>
    </html>
  );
}
